#!/bin/bash
# This file must be used with "source activate"

python3 -m venv .venv
source .venv/bin/activate
python3 -m pip -q install -U -r requirements.txt
if [[ "$GITHUB_ACTIONS" != "true" ]]; then
  pre-commit install
fi
