#!/usr/bin/fakeroot /bin/bash

PREFIX=${PREFIX:-/opt/amiga}

mkdir -p ${PREFIX} || exit 1
./toolchain-m68k build --prefix=${PREFIX}
mkdir -p debian/tmp/${PREFIX}
cp -a ${PREFIX}/* debian/tmp/${PREFIX}/
make -f ./debian/rules binary
make -f ./debian/rules clean
